run:
  deadline: 2m
  skip-files:
    - ^unsecured/

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 16
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: 60 # default 60
    statements: 40 # default 40
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/pkg/errors
  godox:
    keywords:
      - FIXME
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
    settings:
      hugeParam:
        sizeThreshold: 100
  forbidigo:
    forbid:
      - '^print(ln)?$'
      - '^panic$'
      - '^spew\.Print(f|ln)?$'
      - '^spew\.Dump$'

linters:
  enable-all: true
  disable:
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - golint # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - gas
    - dupl
    - prealloc
    - scopelint
    - wsl
    - nlreturn
    - gomnd
    - testpackage
    - paralleltest
    - tparallel
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustivestruct
    - noctx
    - makezero
    - varnamelen

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: version.go
      text: '(version|commit|date) is a global variable'
    - path: label/label_test.go
      text: "string `(carotte|courgette|tomate|type/carotte)` has (\\d+) occurrences, make it a constant"
    - path: gcg.go
      text: "Function 'main' is too long"
    - path: version.go
      text: "use of `fmt.Printf` forbidden by pattern"
