version: 2

project_name: gcg

builds:
  - binary: gcg
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7

    ignore:
      - goos: openbsd
        goarch: arm

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: gcg
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    formats: [ 'tar.gz' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENCE

aurs:
  - description: A GitHub Changelog Generator.
    homepage: https://github.com/ldez/gcg
    skip_upload: false
    provides:
      - gcg
    maintainers:
      - "Fernandez Ludovic <lfernandez dot dev at gmail dot com>"
    license: APACHE
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/gcg-bin.git"
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    package: |-
      # bin
      install -Dm755 "./gcg" "${pkgdir}/usr/bin/gcg"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/gcg/LICENSE"

brews:
  - description: GitHub Changelog Generator
    homepage: https://github.com/ldez/gcg
    skip_upload: false
    repository:
      owner: ldez
      name: homebrew-tap
    directory: Formula
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
    test: |
      system "#{bin}/gcg version"

scoops:
  - description: GitHub Changelog Generator
    homepage: https://github.com/ldez/gcg
    skip_upload: false
    license: APACHE
    repository:
      owner: ldez
      name: scoop-bucket
    commit_author:
      name: ldez
      email: ldez@users.noreply.github.com
