Owner = "containous"
RepositoryName = "traefik"
# GitHubToken = "XXXXXXXXXXXXXXXXX" # optional

OutputType = "file"
FileName = "traefik_changelog.md"

# example new bugfix v1.6.6
CurrentRef = "v1.6"
PreviousRef = "v1.6.5"
BaseBranch = "v1.6"
FutureCurrentRefName = "v1.6.6"

ThresholdPreviousRef = 10
ThresholdCurrentRef = 10

Debug = true
DisplayLabel = true

LabelExcludes = ["area/infrastructure"]
LabelEnhancement = "kind/enhancement"
LabelDocumentation = "area/documentation"
LabelBug = "kind/bug/fix"

[DisplayLabelOptions]
  FilteredPrefixes = ["area/", "platform/"]
  ExcludedSuffixes = ["documentation"]
  TrimmedPrefixes = ["area/provider/", "area/middleware/", "area/", "platform/"]
